# -*- coding: utf-8 -*-
"""PROJETO Sistema Bancário.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-zDOvvqogB7ZnCri3_oJ_lew3Qdc1Pz
"""

print(">>> Bem vindo ao sistema Bancário<<<")

contas = []

def criar_conta():
    verificador_conta_existente = False
    dados_nova_conta = {}
    dados_nova_conta['numero_conta'] = input('Digite o número da nova conta: \n>>>')

    for conta_em_consulta in contas:
      if conta_em_consulta['numero_conta'] == dados_nova_conta['numero_conta']:
        verificador_conta_existente = True
        break

    if verificador_conta_existente == True:
      print('\nXX O número da conta já existe. Tente novamente XX')
    else:
      dados_nova_conta['saldo_conta'] = float(input('Digite o saldo da nova conta: \n>>>'))
      contas.append(dados_nova_conta)
      print('\nOperação efetuada com sucesso')

def remover_conta():
    numero_conta = input('Digite o número da conta para remover: \n>>>')
    conta_encontrada = False
    for conta_em_consulta in contas:
      if conta_em_consulta['numero_conta'] == numero_conta:
        conta_encontrada = True
        contas.remove(conta_em_consulta)
        print('\nOperação efetuada com sucesso')
        break
    if not conta_encontrada:
      print("\n XX Está conta não exite. Tente novamente. XX")

def listar_contas():
  if len(contas) == 0:
    print('\nXX Não há contas cadastradas XX')
  else:
    index = 1
    for conta_em_consulta in contas:
      if conta_em_consulta['saldo_conta'] >= 0:
        status = 'Positivo'
      else:
        status = 'Negativo'
      print(f'Lista de contas: \n{index} - Número da conta: {conta_em_consulta["numero_conta"]} | Saldo da conta: R$ {conta_em_consulta["saldo_conta"]:.2f} ({status})')
      index += 1


def adicionar_saldo_em_conta():
  numero_conta = input('Digite o número da conta: \n>>>')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_credito = float(input('Digite o valor do crédito: \n>>> R$ '))
      if valor_credito < 0:
        print('\nXX Valores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] += valor_credito
        print('\nOperação efetuada com sucesso')
        return
  print('\nXX O número da conta não foi encontrado. Tente novamente. XX')

def remover_saldo_em_conta():
    numero_conta = input('Digite o número da conta: \n>>>')
    for conta_em_consulta in contas:
      if conta_em_consulta['numero_conta'] == numero_conta:
        valor_debito = float(input('Digite o valor que deseja remover do crédito: \n>>> R$ '))
        if valor_debito < 0:
          print('\nXX Valores negativos não são aceitos. Tente novamente.')
          return
        else:
          conta_em_consulta['saldo_conta'] -= valor_debito
          print('\nOperação efetuada com sucesso')
          return
    print('\nXX O número da conta não foi encontrado. Tente novamente. XX')



def transferir_saldo_entre_contas():
    conta_partida = input('Digite o número da sua conta: \n>>>')
    verificador_etapa = 0
    # Procura a primeira conta
    for conta_em_consulta in contas:
        if conta_em_consulta['numero_conta'] == conta_partida:
          verificador_etapa == 1
          conta_destino = input('Digite o número da conta destino: \n>>>')
          # Verifica a se a transferencia não é para mesma conta
          if conta_destino != conta_partida:
            # Procura a segunda conta
            for conta_destino_em_consulta in contas:
              if conta_destino_em_consulta['numero_conta'] == conta_destino:
                verificador_etapa = 3
                valor_transferencia = float(input('Digite o valor da tansferencia: \n>>> R$'))
              # Verifica se o valor é negativo
                if valor_transferencia < 0:
                  print('\nXX Não é possivel transeferir um valor negativo. XX')
                  break
              # Verifica se  o saldo é suficiente
              elif valor_transferencia > conta_em_consulta['saldo_conta']:
                print("\n XX Não é possivel transferir um valor maior que seu saldo. Tente novamente. XX")
                break
        else:
          conta_em_consulta['saldo_conta'] -= valor_transferencia
          conta_destino_em_consulta['saldo_conta'] += valor_transferencia
          print('\nOperação concluida')
          break


    else:
      ferificador_etapa = 2

    if verificador_etapa == 0:
      print('\nXX A sua conta nao foi encontrada. Tente novamente XX')
    elif verificador_etapa == 1:
      print ('\nXX conta de destino não foi encontrada. Tente novamente XX')
    elif verificador_etapa == 2:
      print('\nXX Não é possivel transferir para a mesma conta XX')

def consultar_saldo_de_conta():
  numero_conta = input('Digite o número da conta para consultar o saldo: \n >>>')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      if conta_em_consulta['saldo_conta'] >= 0:
        status = 'Positivo'
      else:
        status = 'Negativo'
      print(f'\nO saldo é: R$ {conta_em_consulta["saldo_conta"]:.2f} ({status})')
      return
  print('\nXX O número da conta não foi encontrado. Tente novamente. XX')

while True:
  print("\n### Menu ###")
  print("0 - Sair")
  print("1 - Criar uma nova conta")
  print("2 - Remover conta")
  print("3 - Listar contas")
  print("4 - Adicionar saldo")
  print("5 - Remover saldo")
  print("6 - Trasferir saldo")
  print("7 - Consultar saldo de uma conta")
  numero_operacao = input('Selecoine a operação que deseja realizar:\n>>>')

# Operação 0 - Encerrar sitemma
  if numero_operacao == "0":
    print('\nSistema encerrado.')
    break

# Operação 1 - Criar uma nova conta
  elif numero_operacao == "1":
    criar_conta()

# Operação 2 - Remover conta
  elif numero_operacao == '2':
   remover_conta()

# Operação 3 - Lista de contas
  elif numero_operacao == '3':
    listar_contas()

# Operação 4 - Adicionar saldo
  elif numero_operacao == '4':
    adicionar_saldo_em_conta()

# Operação 5 - Remover saldo
  elif numero_operacao == '5':
    remover_saldo_em_conta()

# Operação 6 - Transferir saldo
  elif numero_operacao == '6':
    transferir_saldo_entre_contas()

# Operação 7 - Consultar saldo de uma conta
  elif numero_operacao == '7':
    consultar_saldo_de_conta()

# Operação invalida
  else:
    print('\nXX Operação inválida XX.')